#!/usr/bin/env python3
"""JSONL to HTML report generator for SysGuard."""

import json
import html
import sys
import os
import datetime

SEVERITY_MAP = {
    4: "CRITICAL",
    3: "HIGH",
    2: "MEDIUM",
    1: "LOW"
}

SEVERITY_COLORS = {
    "CRITICAL": "#dc3545", # Red
    "HIGH":     "#fd7e14", # Orange
    "MEDIUM":   "#ffc107", # Yellow
    "LOW":      "#0d6efd", # Blue
}


def format_ts(ts_ns):
    if not ts_ns:
        return ""
    try:
        dt = datetime.datetime.fromtimestamp(ts_ns / 1e9)
        return dt.strftime('%Y-%m-%dT%H:%M:%S')
    except Exception:
        return str(ts_ns)
    
def format_type(t):
    if t == 1: return "SYSGUARD_EVENT_EXEC"
    if t == 2: return "SYSGUARD_EVENT_OPEN"
    return str(t)   
    

def jsonl_to_html(jsonl_path: str) -> str:
    html_path = jsonl_path.replace(".jsonl", ".html")
    with open(jsonl_path, "r") as f:
        lines = [json.loads(line) for line in f if line.strip()]

    alerts = [e for e in lines if e.get("alert")]
    events = [e for e in lines if not e.get("alert")]

    summary = {}
    for a in alerts:
        sev_int = a.get("severity", 1)
        sev_str = SEVERITY_MAP.get(sev_int, "LOW")
        summary[sev_str] = summary.get(sev_str, 0) + 1

    content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SysGuard Report</title>
<style>
body {{ font-family: 'Segoe UI', sans-serif; margin: 2rem; background: #f8f9fa; }}
h1 {{ color: #1a3a5c; border-bottom: 3px solid #1a3a5c; padding-bottom: 0.5rem; }}
h2 {{ color: #333; margin-top: 2rem; }}
.summary {{ display: flex; gap: 1rem; margin: 1rem 0; }}
.card {{ padding: 1rem 1.5rem; border-radius: 8px; color: white; font-size: 1.2rem; min-width: 120px; text-align: center; }}
table {{ border-collapse: collapse; width: 100%; margin-top: 0.5rem; background: white; }}
th, td {{ border: 1px solid #dee2e6; padding: 0.5rem 0.75rem; text-align: left; font-size: 0.85rem; }}
th {{ background: #1a3a5c; color: white; }}
tr:nth-child(even) {{ background: #f2f2f2; }}
.sev {{ font-weight: bold; padding: 2px 8px; border-radius: 4px; color: white; }}
.meta {{ color: #888; font-size: 0.8rem; margin-top: 2rem; }}
</style>
</head>
<body>
<h1>🛡️ SysGuard Security Report</h1>
<p>Source: <code>{html.escape(os.path.basename(jsonl_path))}</code>
 — Total events: {len(lines)}, Alerts: {len(alerts)}</p>
<div class="summary">
"""
    # 4단계 심각도 순서대로 요약 카드 생성
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        cnt = summary.get(sev, 0)
        color = SEVERITY_COLORS.get(sev, "#666")
        content += f'  <div class="card" style="background:{color}">{sev}<br><b>{cnt}</b></div>\n'

    content += "</div>\n"

    if alerts:
        content += "<h2>⚠️ Alerts</h2>\n<table>\n"
        # 헤더 이름을 C 구조체 필드명과 맥락에 맞게 Rule ID, Reason, Path 등으로 수정
        content += "<tr><th>Time</th><th>Severity</th><th>Rule ID</th><th>PID</th><th>Command</th><th>Target Path</th><th>Reason</th></tr>\n"
        for a in alerts:
            sev_int = a.get("severity", 1)
            sev_str = SEVERITY_MAP.get(sev_int, "LOW")
            color = SEVERITY_COLORS.get(sev_str, "#666")
            time_str = format_ts(a.get("timestamp_ns"))
            target_path = a.get("exe_path", "") or a.get("path", "")
            content += (
                f"<tr><td>{html.escape(time_str)}</td>"
                f"<td><span class='sev' style='background:{color}'>{sev_str}</span></td>"
                f"<td>{html.escape(a.get('rule_id',''))}</td>"
                f"<td>{a.get('pid','')}</td>"
                f"<td>{html.escape(a.get('comm',''))}</td>"
                f"<td>{html.escape(target_path)}</td>"
                f"<td>{html.escape(a.get('reason',''))}</td></tr>\n"
            )
        content += "</table>\n"

    if events:
        content += "<h2>📋 Events (no alert)</h2>\n<table>\n"
        content += "<tr><th>Time</th><th>Type</th><th>PID</th><th>UID</th><th>Command</th><th>Target Path</th></tr>\n"
        for e in events:
            time_str = format_ts(e.get("timestamp_ns"))
            target_path = e.get("exe_path", "") or e.get("path", "")
            type_str = format_type(e.get("type"))

            content += (
                f"<tr><td>{html.escape(time_str)}</td>"
                f"<td>{html.escape(type_str)}</td>"
                f"<td>{e.get('pid','')}</td>"
                f"<td>{e.get('uid','')}</td>"
                f"<td>{html.escape(e.get('comm',''))}</td>"
                f"<td>{html.escape(target_path)}</td></tr>\n"
            )
        content += "</table>\n"

    content += '<p class="meta">Generated by SysGuard Report Engine</p>\n</body></html>'

    with open(html_path, "w") as f:
        f.write(content)
    return html_path


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 report.py <session.jsonl>")
        sys.exit(1)
    path = jsonl_to_html(sys.argv[1])
    print(f"Report generated: {path}")